//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication9
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_details
    {
        public int emp_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> date_of_joining { get; set; }
        public string location { get; set; }
    }
}
