USE [master]
GO

/****** Object:  Database [workshop]    Script Date: 17-03-2019 10:07:49 PM ******/
CREATE DATABASE [workshop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'workshop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\workshop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'workshop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\workshop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [workshop] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [workshop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [workshop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [workshop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [workshop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [workshop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [workshop] SET ARITHABORT OFF 
GO

ALTER DATABASE [workshop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [workshop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [workshop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [workshop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [workshop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [workshop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [workshop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [workshop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [workshop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [workshop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [workshop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [workshop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [workshop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [workshop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [workshop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [workshop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [workshop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [workshop] SET RECOVERY FULL 
GO

ALTER DATABASE [workshop] SET  MULTI_USER 
GO

ALTER DATABASE [workshop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [workshop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [workshop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [workshop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [workshop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [workshop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [workshop] SET  READ_WRITE 
GO


create table employee_details(emp_id int primary key,
name varchar(50),
DOB date,
age int,
date_of_joining date,
location varchar(30));
